<?php
/*
 * Slovenian language file for the message labels plugin
 * to enable forward / out of office replies.
 *
 * @package        plugins
 * @uses        rcube_plugin
 * @author       Gregor Gresak razvoj@gresak.net 
 * @version        1.0
 * @license     GPL
 * @link        https://github.com/gresakg/rcubevacation-virtualmin
*/
$labels['label_title'] = 'Oznake';
$labels['label_create'] = 'Ustvari oznako';
$labels['label_set'] = 'Označi kot';
$labels['label_matches'] = 'zadetkov';
$labels['label_color'] = 'barva';
$labels['label_delete'] = 'zbriši';
$labels['label_name'] = 'ime';
$labels['label_folder'] = 'išči v ';
$labels['label_all'] = 'Vse mape';
$labels['label_pref'] = 'Upravljanje oznak';
$labels['help_filter_caption'] = "Pomoč";
$labels['label_help_filter'] = 'S pomočjo %snastavitve filtrov%s lahko nastaviš samodejno označevanje elektronske pošte';

$labels['deleteconfirm'] = 'Ali resnično želiš odstraniti oznako?';
$labels['add_row'] = 'dodaj';
$labels['delete_row'] = 'zbriši';

$labels['headererror'] = 'Napaka v nastavitvi pravila';
$labels['inputempty'] = 'Eden ali več zadetkov je prazen';
$labels['invalidcolor'] = 'Neveljavna barva';

$labels['check_highlighting'] = 'Preverjam delovanje načina barv';
$labels['highlighting'] = 'Način barv';

$labels['check_labels'] = 'Preverjam delovanje načina oznak';
$labels['labels'] = 'Način oznak';

$labels['check_error'] = 'Napaka pri preverjanju načina';

$labels['label_mode'] = 'Način prikaza';
$labels['search_info'] = 'Informacije o iskanju';

$labels['display_label_on'] = 'Prikaz seznama oznak vključen';
$labels['display_label_off'] = 'Prikaz seznama oznak izključen';

?>
